### ISSUE TITLE
Cannot get any data

### ISSUE THREAD

**Issue by MuyBien** [SHARANTANGEDA/windy_crawler#1]
Hi!

I tried to use your script but I have an error no matter which location I choose:

```
#########################Weather Forecast for 5 days##############################
=>Mercredi 20
Spider error processing <GET https://www.windy.com> (referer: None)
Traceback (most recent call last):
  File "/home/fred/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/fred/.local/lib/python3.6/site-packages/windy_crawler/spiders/forecast_spider.py", line 137, in parse
    airport=view_bar[suggestions_index[select_index] - 1])
  File "/home/fred/.local/lib/python3.6/site-packages/windy_crawler/spiders/forecast_spider.py", line 62, in get_forecast_data
    ind = times_list.index('0AM')
ValueError: '0AM' is not in list
```

Do you know what cause this? 
I am on Ubuntu 18.04 with Python 3.6.9

Thanks!

**Comment by MuyBien** [comment]
I think it has to be the locale... :thinking:   
How to change that?

**Comment by SHARANTANGEDA** [comment]
Hi, I just checked the site now.
The website has been updated, hence changing HTML of the page
That is the reason you are not able to get any data
You can give it a try, it is just changing the HTML class names and editing a few lines of code
Unfortunately, I'm currently hung up on other projects so I can't update the code now

Hope this helps & thanks for the raising the issue

**Comment by MuyBien** [comment]
OK thanks. I will take a look at the code :+1:   
Thanks. Maybe I will ask you for some questions ^^
